### ISSUE TITLE
ARFoundationDemos folder is empty

### ISSUE THREAD

**Issue by alexchouls** [Unity-Technologies/arfoundation-demos#31]
Are there any demo scenes? No build scenes?
I would expect a project that you could build and run after cloning...

**Comment by DanMillerDev** [comment]
There are several demo scenes, I've remove them from the build settings due to the way the project is split up when packaging them out for the asset store. Each project is split into it's old folder and subfolders that contain a Scenes folder. 

[UXManagerScene](https://github.com/Unity-Technologies/arfoundation-demos/blob/master/Assets/UX/Scenes/UXManagerScene.unity)
[ImageTracking](https://github.com/Unity-Technologies/arfoundation-demos/blob/master/Assets/ImageTracking/Scenes/ImageTracking.unity)
[Mesh Placement](https://github.com/Unity-Technologies/arfoundation-demos/blob/master/Assets/Meshing/Scenes/Meshing.unity)

I can readd them to the build settings if that makes it easier. The shaders each have their own scenes too but require assigning the URP asset to graphics settings.

**Comment by DanMillerDev** [comment]
https://github.com/Unity-Technologies/arfoundation-demos/commit/91d18cc0f629e2b129bdcc56b86e572c6a21fd25

I've deleted the empty folder and added scenes to the build settings, a new clone or a pull should get these changes and you can build and run to an ARKit or ARCore supported device.

**Comment by alexchouls** [comment]
Thanks! I think it was the empty folder more than anything that confused
me. It was the first place I looked. But I did find the scenes eventually...

Cheers,
Alex
